# Generated by Django 4.0.4 on 2022-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_casa', models.CharField(max_length=50, verbose_name='Proyecto Al Que Pertenece')),
                ('modelo_casa', models.CharField(max_length=50, verbose_name='Modelo De Casa')),
                ('poligono_casa', models.CharField(max_length=50, verbose_name='Poligono De Casa')),
                ('numero_casa', models.IntegerField(verbose_name='Numero De Casa')),
                ('contratista_casa', models.CharField(max_length=50, verbose_name='Contratista De La Casa')),
                ('estado_contratista', models.BooleanField(verbose_name='Estado Del Contratista')),
                ('obra_casa', models.CharField(max_length=50, verbose_name='Codigo De Obra')),
                ('agrupacion_casa', models.CharField(max_length=100, verbose_name='Agrupacion')),
                ('precio_agru', models.FloatField(verbose_name='Precio De La Agrupacion $ ')),
                ('porcentaje_casa', models.FloatField(verbose_name='Porcentaje %')),
                ('content', models.TextField(blank=True, verbose_name='Comentarios')),
                ('progreso_casa', models.IntegerField(verbose_name='Progreso De La Casa')),
                ('fecha_generica', models.CharField(max_length=50, verbose_name='Fecha Generica')),
                ('creado_user', models.CharField(max_length=50, verbose_name='Creado Por ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Creacion El')),
                ('update_user', models.CharField(max_length=50, verbose_name='Actualizado Por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha De Actualizacion')),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
        ),
    ]
