# Generated by Django 4.0.4 on 2022-08-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_contratista_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratista',
            options={'verbose_name': 'Contratista', 'verbose_name_plural': '🦺 Contratistas'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Registro', 'verbose_name_plural': '🗃️ Nueva San Miguel'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='proyecto_casa',
        ),
    ]
