# Generated by Django 4.0.4 on 2022-08-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_contratista_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contratista',
        ),
    ]
