# Generated by Django 4.0.4 on 2022-08-19 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_delete_contratista'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='vales_casa',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
