# Generated by Django 4.0.4 on 2022-08-19 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_page_vales_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='vales_casa',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)], verbose_name='Vales Entregados'),
        ),
    ]
