# Generated by Django 4.0.4 on 2022-08-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_proyecto2_alter_page_fecha_generica_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AlterModelOptions(
            name='proyecto2',
            options={'verbose_name': 'Registro', 'verbose_name_plural': '🗃️ EcoTerra Maquilishuat'},
        ),
    ]
