# Generated by Django 4.0.4 on 2022-08-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_delete_page_alter_proyecto2_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto2',
            new_name='Proyecto1',
        ),
    ]
