# Generated by Django 3.2.15 on 2022-09-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_remove_proyecto1_progreso_casa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto1',
            options={'verbose_name': 'Registro', 'verbose_name_plural': '🗃️ Nueva San Miguel'},
        ),
        migrations.RemoveField(
            model_name='proyecto1',
            name='creado_user',
        ),
        migrations.RemoveField(
            model_name='proyecto1',
            name='fecha_generica',
        ),
        migrations.RemoveField(
            model_name='proyecto1',
            name='update_user',
        ),
    ]
