# Generated by Django 4.0.4 on 2022-09-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_auto_20220901_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='orden_casa',
            field=models.CharField(default=1, max_length=50, verbose_name='N° De Orden'),
            preserve_default=False,
        ),
    ]
