# Generated by Django 4.0.4 on 2022-09-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_proyecto1_orden_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto1',
            name='precio_agru',
            field=models.FloatField(default='111111', editable=False, verbose_name='Precio De La Agrupacion $ '),
        ),
    ]
