# Generated by Django 4.0.4 on 2022-09-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_alter_proyecto1_precio_agru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto1',
            name='precio_agru',
            field=models.FloatField(default='111111', verbose_name='Precio De La Agrupacion $ '),
        ),
    ]
