# Generated by Django 4.0.4 on 2022-09-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_alter_proyecto1_precio_agru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto1',
            name='agrupacion_casa',
        ),
        migrations.RemoveField(
            model_name='proyecto1',
            name='precio_agru',
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='estado_contratista',
            field=models.BooleanField(help_text='Contratista Activo O Inactivo', verbose_name='Estado Del Contratista'),
        ),
    ]
