# Generated by Django 4.0.4 on 2022-09-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0018_alter_proyecto1_contratista_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='cluster_casa',
            field=models.CharField(default=1, max_length=100, verbose_name='Cluster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='contratista_casa',
            field=models.CharField(max_length=100, verbose_name='Contratista'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='modelo_casa',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='obra_casa',
            field=models.CharField(choices=[('N°1 (Textury)  / Precio: $752 / Precio C:  $275,06', '1'), ('N°2 (Pintura) / Precio: 2359.0 / Precio C: 4512.0', '2'), ('N°3 (Estuco) / Precio: 150.0 / Precio C: 150.0', '3'), ('N°4 (Resanes) / Precio: $1234.0 / Precio C: $1234.0', '4')], max_length=100, verbose_name='Codigo De Obra'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='orden_casa',
            field=models.CharField(max_length=100, verbose_name='N° De Orden'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='poligono_casa',
            field=models.CharField(max_length=100, verbose_name='Poligono'),
        ),
    ]
