# Generated by Django 4.0.4 on 2022-09-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_proyecto1_cluster_casa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto1',
            name='vales_casa',
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='obra_casa',
            field=models.CharField(choices=[('N°1 (Textury)  / Precio C:  $275,06', '1'), ('N°2 (Pintura) / Precio C: 4512.0', '2'), ('N°3 (Estuco) /  Precio C: 150.0', '3'), ('N°4 (Resanes) / Precio C: $1234.0', '4')], max_length=100, verbose_name='Codigo De Obra'),
        ),
    ]
