# Generated by Django 4.0.4 on 2022-09-07 09:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_remove_proyecto1_vales_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='estado_casa',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Inicio ', 'Inicio'), ('Final', 'Final')], default=1, max_length=13, verbose_name='Orden De Trabajo'),
            preserve_default=False,
        ),
    ]
