# Generated by Django 4.0.4 on 2022-09-07 10:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_proyecto1_estado_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='num_planilla',
            field=models.IntegerField(default=1, verbose_name='Numero De Planilla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='estado_casa',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Inicio', 'Inicio'), ('Cobro', 'Cobro'), ('Final', 'Final')], max_length=18, verbose_name='Orden De Trabajo'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='estado_contratista',
            field=models.BooleanField(default=False, help_text='Activo / Inactivo', verbose_name='Cambio De Contratista'),
        ),
    ]
