# Generated by Django 4.0.4 on 2022-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_proyecto1_num_planilla_alter_proyecto1_estado_casa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto1',
            name='num_planilla',
            field=models.CharField(default='PLANILLA N°', max_length=100, verbose_name='Planilla'),
        ),
    ]
