# Generated by Django 4.0.4 on 2022-09-12 10:48

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0024_proyecto1_suministros_casa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto1',
            options={'verbose_name': 'Registro', 'verbose_name_plural': '🗃️ Eco Terra Maquilishuat'},
        ),
        migrations.RemoveField(
            model_name='proyecto1',
            name='obra_casa',
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='cluster_casa',
            field=models.CharField(max_length=100, verbose_name='Cluster:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='content',
            field=models.TextField(blank=True, help_text='Si No Tiene Comentarios Puede Dejar Este Campo Vacio', verbose_name='Comentarios:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='contratista_casa',
            field=models.CharField(choices=[('Josue Vega', 'Josue Vega'), ('Ricardo Martinez', 'Ricardo Martinez'), ('Ricardo Vega', 'Ricardo Vega')], max_length=100, verbose_name='Contratista:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Creacion El:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='estado_casa',
            field=models.CharField(choices=[('Inicio', 'Inicio'), ('Cobro', 'Cobro'), ('Final', 'Final')], default=('Inicio', 'Inicio'), help_text='Seleccion Del Estado En Que Se Encuentra La Obra', max_length=100, verbose_name='Orden De Trabajo:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='estado_contratista',
            field=models.BooleanField(default=False, help_text='Si / No', verbose_name='Cambio De Contratista:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='modelo_casa',
            field=models.CharField(max_length=100, verbose_name='Modelo:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='num_planilla',
            field=models.CharField(default='P', help_text='Numero De Planilla - Ejemplo:(P1)', max_length=100, verbose_name='Planilla:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='numero_casa',
            field=models.IntegerField(verbose_name='Numero De Casa:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='orden_casa',
            field=models.CharField(max_length=100, verbose_name='N° De Orden:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='poligono_casa',
            field=models.CharField(max_length=100, verbose_name='Poligono:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='porcentaje_casa',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje %:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='suministros_casa',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Estuco', 'Estuco'), ('Resanes', 'Resanes'), ('Textury', 'Textury'), ('Pintura', 'Pintura'), ('Resanes / Textury / Pintura', 'Resanes / Textury / Pintura')], default=('Estuco', 'Estuco'), help_text='Este Campo Incluye (Resanes,Textury,Pinturas)', max_length=58, verbose_name='Suministros De Materiales:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha De Actualizacion:'),
        ),
    ]
