# Generated by Django 4.0.4 on 2022-09-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0026_proyecto1_contratista2_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='estado_final',
            field=models.BooleanField(default=False, help_text='Si / No', verbose_name='Obra Finalizada:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='contratista2_casa',
            field=models.CharField(choices=[('Josue Martinez', 'Josue Martinez'), ('Josue Vega', 'Josue Vega'), ('Ricardo Martinez', 'Ricardo Martinez'), ('Ricardo Vega', 'Ricardo Vega')], max_length=100, verbose_name='Contratista De Pintura:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='contratista_casa',
            field=models.CharField(choices=[('Josue Martinez', 'Josue Martinez'), ('Josue Vega', 'Josue Vega'), ('Ricardo Martinez', 'Ricardo Martinez'), ('Ricardo Vega', 'Ricardo Vega')], max_length=100, verbose_name='Contratista De Estuco:'),
        ),
    ]
