# Generated by Django 4.0.4 on 2022-09-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0027_proyecto1_estado_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='fecha_final',
            field=models.CharField(default=1, editable=False, max_length=100, verbose_name='Fecha De Actualizacion:'),
            preserve_default=False,
        ),
    ]
