# Generated by Django 4.0.4 on 2022-09-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0028_proyecto1_fecha_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='upload',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='estado_casa',
            field=models.CharField(choices=[('Inicio', 'Inicio'), ('Cobro', 'Cobro'), ('Final', 'Final')], default=('Inicio', 'Inicio'), help_text='Una Vez Finalizado No Se Podra Realizar Cambios', max_length=100, verbose_name='Orden De Trabajo:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='estado_final',
            field=models.BooleanField(default=False, editable=False, help_text='Si / No', verbose_name='Obra Finalizada:'),
        ),
    ]
