# Generated by Django 4.0.4 on 2022-09-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0029_proyecto1_upload_alter_proyecto1_estado_casa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto1',
            name='upload',
        ),
        migrations.AddField(
            model_name='proyecto1',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Foto:'),
        ),
    ]
