# Generated by Django 4.0.4 on 2022-09-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0030_remove_proyecto1_upload_proyecto1_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto1',
            name='avatar',
        ),
    ]
