# Generated by Django 4.0.4 on 2022-09-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0031_remove_proyecto1_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto1',
            options={'verbose_name': 'Registro', 'verbose_name_plural': '🗃️ Nueva San Miguel'},
        ),
    ]
