# Generated by Django 4.0.4 on 2022-09-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0032_alter_proyecto1_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto1',
            name='obra',
            field=models.ManyToManyField(related_name='sandwiches', to='proyectos.sauce'),
        ),
    ]
