# Generated by Django 4.0.4 on 2022-09-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0034_agrupaciones_delete_sauce_alter_proyecto1_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agrupaciones',
            name='content',
        ),
    ]
