# Generated by Django 4.0.4 on 2022-09-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0035_remove_agrupaciones_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto1',
            name='suministros_casa',
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='obra',
            field=models.ManyToManyField(to='proyectos.agrupaciones', verbose_name='Codigo De Obra'),
        ),
    ]
