# Generated by Django 4.0.4 on 2022-09-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0036_remove_proyecto1_suministros_casa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('dui_persona', models.CharField(max_length=100, unique=True, verbose_name='Dui')),
                ('nit_persona', models.CharField(max_length=100, unique=True, verbose_name='Nit')),
                ('tel_persona', models.CharField(blank=True, default='0000-0000', max_length=9, unique=True, verbose_name='Telefono')),
                ('estado_contratista', models.BooleanField(default=True, verbose_name='Estado Del Contratista')),
                ('content', models.TextField(blank=True, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El ')),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': '🦺 Contratistas',
            },
        ),
    ]
