# Generated by Django 4.0.4 on 2022-09-27 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0038_alter_proyecto1_contratista2_casa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto1',
            options={'verbose_name': 'Registro', 'verbose_name_plural': '📦 Nueva San Miguel'},
        ),
        migrations.AddField(
            model_name='proyecto1',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='porcentaje_casa',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje %:'),
        ),
    ]
