# Generated by Django 4.0.4 on 2022-09-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0039_alter_proyecto1_options_proyecto1_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto1',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio:'),
        ),
    ]
