# Generated by Django 4.0.4 on 2022-09-27 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0040_alter_proyecto1_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='subtotal',
            field=models.FloatField(default=0, verbose_name='Sub total: $'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='porcentaje_casa',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje %:'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Obra: $'),
        ),
    ]
