# Generated by Django 4.0.4 on 2022-09-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0041_proyecto1_subtotal_alter_proyecto1_porcentaje_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrupaciones',
            name='modelo_casa',
            field=models.CharField(default=1, max_length=100, verbose_name='Modelo:'),
            preserve_default=False,
        ),
    ]
