# Generated by Django 4.0.4 on 2022-09-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0042_agrupaciones_modelo_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='total_casa',
            field=models.FloatField(default=0, verbose_name='Total: $'),
        ),
    ]
