# Generated by Django 4.0.4 on 2022-09-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0043_proyecto1_total_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupaciones',
            name='nombre_agru',
            field=models.CharField(default='AGRUPACION N°', max_length=100, verbose_name='Agrupacion'),
        ),
        migrations.AlterField(
            model_name='proyecto1',
            name='subtotal',
            field=models.FloatField(default=0, verbose_name='Sub Total: $'),
        ),
    ]
