# Generated by Django 4.0.4 on 2022-09-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0044_alter_agrupaciones_nombre_agru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='image',
            field=models.ImageField(default='null', upload_to='articles', verbose_name='Imagen'),
        ),
    ]
