# Generated by Django 4.0.4 on 2022-09-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0045_proyecto1_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto1',
            name='image',
        ),
    ]
