# Generated by Django 4.0.4 on 2022-10-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0047_alter_proyecto1_options_proyecto1_recopilacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto1',
            name='recopilacion',
        ),
    ]
