# Generated by Django 4.0.4 on 2022-10-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0048_remove_proyecto1_recopilacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Codigo De Obra')),
                ('modelo_casa', models.CharField(max_length=100, verbose_name='Modelo:')),
                ('kit', models.CharField(max_length=100, verbose_name='Kit De Vivienda')),
                ('unidad_medida', models.CharField(max_length=100, verbose_name='Unidad De Medida')),
                ('precio_cobro', models.FloatField(default=0, verbose_name='Precio Cobro')),
                ('precio_pago', models.FloatField(default=0, verbose_name='Precio Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El ')),
            ],
            options={
                'verbose_name': 'Adicional',
                'verbose_name_plural': 'Adicionales',
            },
        ),
        migrations.AlterModelOptions(
            name='agrupaciones',
            options={'verbose_name': 'Codigo De Obra', 'verbose_name_plural': ' Codigos De Obra'},
        ),
        migrations.AlterModelOptions(
            name='contratista',
            options={'verbose_name': 'Contratista', 'verbose_name_plural': 'Contratistas'},
        ),
        migrations.AlterModelOptions(
            name='proyecto1',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Nueva San Miguel'},
        ),
    ]
