# Generated by Django 4.0.4 on 2022-10-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0049_adicionales_alter_agrupaciones_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto1',
            name='adicional',
            field=models.ManyToManyField(to='proyectos.adicionales', verbose_name='Codigo De Obra (Adicional)'),
        ),
        migrations.AddField(
            model_name='proyecto1',
            name='contratista3_casa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='opcion3', to='proyectos.contratista', verbose_name='Contratista Adicional:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto1',
            name='porcentaje_casa2',
            field=models.FloatField(default=0, verbose_name='Porcentaje Adicional %:'),
        ),
    ]
