# Generated by Django 4.0.4 on 2022-10-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0051_remove_proyecto1_adicional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto1_adicional',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Nueva San Miguel (Add)'},
        ),
        migrations.RemoveField(
            model_name='proyecto1_adicional',
            name='contratista2_casa',
        ),
    ]
