# Generated by Django 4.0.4 on 2022-10-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0052_alter_proyecto1_adicional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto1_adicional',
            name='contratista_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opcion1_adicional', to='proyectos.contratista', verbose_name='Contratista'),
        ),
    ]
