# Generated by Django 4.0.4 on 2022-11-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0055_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
