# Generated by Django 4.0.4 on 2022-11-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre:')),
                ('content', models.TextField(verbose_name='Contenido:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El ')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
